//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSuspicious.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WSuspicious.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;s:Envelope xmlns:s=&quot;http://schemas.xmlsoap.org/soap/envelope/&quot;&gt;
        ///    &lt;s:Body xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///        &lt;GetExtendedUpdateInfoResponse xmlns=&quot;http://www.microsoft.com/SoftwareDistribution/Server/ClientWebService&quot;&gt;
        ///            &lt;GetExtendedUpdateInfoResult&gt;
        ///                &lt;Updates&gt;
        ///                    &lt;Update&gt;
        ///                        &lt;ID&gt;{0}&lt;/ID&gt;
        ///                        &lt;Xml&gt;&amp;lt;ExtendedProperties DefaultPropertiesLanguage=&quot;en&quot;  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ExtendedUpdateInfoTemplate {
            get {
                return ResourceManager.GetString("ExtendedUpdateInfoTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;NewUpdates&gt;
        ///	&lt;UpdateInfo&gt;
        ///		&lt;ID&gt;{0}&lt;/ID&gt;
        ///		&lt;Deployment&gt;
        ///			&lt;ID&gt;{1}&lt;/ID&gt;
        ///			&lt;Action&gt;Install&lt;/Action&gt;
        ///			&lt;IsAssigned&gt;true&lt;/IsAssigned&gt;
        ///			&lt;LastChangeTime&gt;2020-02-29&lt;/LastChangeTime&gt;
        ///			&lt;AutoSelect&gt;0&lt;/AutoSelect&gt;
        ///			&lt;AutoDownload&gt;0&lt;/AutoDownload&gt;
        ///			&lt;SupersedenceBehavior&gt;0&lt;/SupersedenceBehavior&gt;
        ///		&lt;/Deployment&gt;
        ///		&lt;IsLeaf&gt;true&lt;/IsLeaf&gt;
        ///		&lt;Xml&gt;&amp;lt;UpdateIdentity UpdateID=&quot;{2}&quot; RevisionNumber=&quot;204&quot; /&amp;gt;&amp;lt;Properties UpdateType=&quot;Software&quot; ExplicitlyDeployable=&quot;true&quot; AutoSelectOnWebSites=&quot;true&quot; /&amp;gt [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NewUpdatesTemplate {
            get {
                return ResourceManager.GetString("NewUpdatesTemplate", resourceCulture);
            }
        }
    }
}
